name: terraform plan

on: push

jobs:
    tf_code_check:
      name: Terraform Validation and Build
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
  
      - name: Configure AWS Credentials Action For GitHub Actions
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      - uses: hashicorp/setup-terraform@v2
      
      - name: Terraform Init
        id: init
        run: terraform init
      
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: true
      
      - name: Terraform apply
        run: terraform apply  --auto-approve  

    #   - name: Terraform destroy
    #     run: terraform destroy  --auto-approve